// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Data.FBObjects
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FBLinkshell : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static FBLinkshell GetRootAsFBLinkshell(ByteBuffer _bb) { return GetRootAsFBLinkshell(_bb, new FBLinkshell()); }
  public static FBLinkshell GetRootAsFBLinkshell(ByteBuffer _bb, FBLinkshell obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FBLinkshell __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public Data.FBCommon.FBColor? Color { get { int o = __p.__offset(8); return o != 0 ? (Data.FBCommon.FBColor?)(new Data.FBCommon.FBColor()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public string Message { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(10); }

  public static void StartFBLinkshell(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddColor(FlatBufferBuilder builder, Offset<Data.FBCommon.FBColor> colorOffset) { builder.AddStruct(2, colorOffset.Value, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(3, messageOffset.Value, 0); }
  public static Offset<Data.FBObjects.FBLinkshell> EndFBLinkshell(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Data.FBObjects.FBLinkshell>(o);
  }
  public static void FinishFBLinkshellBuffer(FlatBufferBuilder builder, Offset<Data.FBObjects.FBLinkshell> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFBLinkshellBuffer(FlatBufferBuilder builder, Offset<Data.FBObjects.FBLinkshell> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
