// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Data.FBCommon
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FBColor : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public FBColor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte Red { get { return __p.bb.GetSbyte(__p.bb_pos + 0); } }
  public sbyte Green { get { return __p.bb.GetSbyte(__p.bb_pos + 1); } }
  public sbyte Blue { get { return __p.bb.GetSbyte(__p.bb_pos + 2); } }

  public static Offset<Data.FBCommon.FBColor> CreateFBColor(FlatBufferBuilder builder, sbyte Red, sbyte Green, sbyte Blue) {
    builder.Prep(1, 3);
    builder.PutSbyte(Blue);
    builder.PutSbyte(Green);
    builder.PutSbyte(Red);
    return new Offset<Data.FBCommon.FBColor>(builder.Offset);
  }
};


}
